type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
}

type Category @table {
  name: String!
  createdAt: Timestamp!
  description: String
}

type Item @table {
  name: String!
  stockQuantity: Int!
  createdAt: Timestamp!
  description: String
  sku: String
  price: Float
  owner: User
  category: Category
}

type StockMovement @table {
  quantityChange: Int!
  movementType: String!
  createdAt: Timestamp!
  notes: String
  item: Item
  recordedBy: User
}